app.message=Hello from config!
app.version=1.0.0
app.author=Ichijo
spring.datasource.url=jdbc:h2:file:./data/todo-db
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=update